export const recommendedTags = [
    "Warmup",
    "Daily_Practice",
    "Weak_Topics",
    "Easy",
    "Medium",
    "Hard",
    "ICPC",
    "Mini_Contest",
    "Strong_Topics",
    "Binary_Search",
    "Brute_Force",
    "Data_Structures",
    "Divide___Conquer",
    "Dynamic_Programming",
    "Greedy",
    "Implementation",
    "Adhoc",
    "Bitmasks",
    "Combinatorics",
    "FFT",
    "Flows___Matching",
    "Games",
    "Geometry",
    "Graphs___Trees",
    "Hashing",
    "Math",
    "Matrices",
    "Number_Theory",
    "Probabilities",
    "Strings",
    "UNTAGGED",
    "Random"
];

export const problemTags = [
    "2-sat",
    "binary search",
    "bitmasks",
    "brute force",
    "chinese remainder theorem",
    "combinatorics",
    "constructive algorithms",
    "data structures",
    "dfs and similar",
    "divide and conquer",
    "dp",
    "dsu",
    "expression parsing",
    "fft",
    "flows",
    "games",
    "geometry",
    "graph matchings",
    "graphs",
    "greedy",
    "hashing",
    "implementation",
    "interactive",
    "math",
    "matrices",
    "meet-in-the-middle",
    "number theory",
    "probabilities",
    "schedules",
    "shortest paths",
    "sortings",
    "string suffix structures",
    "strings",
    "ternary search",
    "trees",
    "two pointers"
];